### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by wesbz** [check-face/facemorph.me#14]
Hi,
I would love to test your project but it seems like nothing is working... Generating from text, uploading, morphing, everything returns an error in console or displays an error message.
Am I the only one facing this?
Thanks in advance

**Comment by olivercoad** [comment]
Hi, sorry I didn't see the issue earlier; I thought I had notifications on for this repo but apparently not.

Unfortunately the server had about a month of downtime but it's back up and running.

**Comment by wesbz** [comment]
Hi, thanks for your response!
No problem ;) Glad to see it working now!
